# Data Processing using Pandas

### 1) What is Data Manipulation and Data Analysis?

- Data Manipulation - Cleaning and transforming raw data into processed data, so that it can be used for data Analysis

- Data Analysis - Finding patterns,trends and insights from processed data so that business problems can be solved

### 2) DataFrame and Series

- Dataframe - Table with columns and rows
- Series - A single column of a DataFrame is called a Series.

### 3) Starting Pandas  

#### 1) How to read files?

In [12]:
import pandas as pd

# How to read the .csv ,.json and excel files

# df=pd.read_csv("sales_data_sample.csv",encoding="latin1")
# df=pd.read_excel("SampleSuperstore.xlsx")
# df=pd.read_json("sample_Data.json")
#print(df)

#### 2) Create Dataframe

In [13]:
# creating sample dataframes
data={
    "name": ["Mangesh", "Rahul", "Amit","Pratik","Aryan","Eshaan"],
    "age": [20, 21, 22,20,19,23],
    "city": ["Pune", "Mumbai", "Nashik","Gujrat","Kashmir","Jammu"],
    "marks":[96,78,71,93,86,81]
}

df=pd.DataFrame(data)
print(df)


# loading dataframes into csv, json and excel files
df.to_csv("output.csv",index=False)
df.to_excel("output2.xlsx",index=False)
df.to_json("output3.json",index=False)

      name  age     city  marks
0  Mangesh   20     Pune     96
1    Rahul   21   Mumbai     78
2     Amit   22   Nashik     71
3   Pratik   20   Gujrat     93
4    Aryan   19  Kashmir     86
5   Eshaan   23    Jammu     81

#### 3) Basic Dataframe Understanding

In [14]:
df.head(2) #otherwise by default, it returns 5 values
# df.tail() # returns last 5 rows

      name  age    city  marks
0  Mangesh   20    Pune     96
1    Rahul   21  Mumbai     78

In [15]:
# df.shape()

In [16]:
# df.columns()

In [17]:
df.rename(columns={'city': 'Home_Town'}, inplace=True) # rename column name/s
df

      name  age Home_Town  marks
0  Mangesh   20      Pune     96
1    Rahul   21    Mumbai     78
2     Amit   22    Nashik     71
3   Pratik   20    Gujrat     93
4    Aryan   19   Kashmir     86
5   Eshaan   23     Jammu     81

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       6 non-null      str
 1   age        6 non-null      int64
 2   Home_Town  6 non-null      str
 3   marks      6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

In [19]:
# describe method generates descriptive statistics of DataFrame, only for numerical-value column
df.describe()

             age      marks
count   6.000000   6.000000
mean   20.833333  84.166667
std     1.471960   9.410986
min    19.000000  71.000000
25%    20.000000  78.750000
50%    20.500000  83.500000
75%    21.750000  91.250000
max    23.000000  96.000000

#### 4) Rows & Columns - Selection

In [20]:
df[['name']] ## select single column

      name
0  Mangesh
1    Rahul
2     Amit
3   Pratik
4    Aryan
5   Eshaan

In [21]:
df[['name','age']] #selects multiple column

      name  age
0  Mangesh   20
1    Rahul   21
2     Amit   22
3   Pratik   20
4    Aryan   19
5   Eshaan   23

In [22]:
# returns multiple rows
df.loc[0:2]

      name  age Home_Town  marks
0  Mangesh   20      Pune     96
1    Rahul   21    Mumbai     78
2     Amit   22    Nashik     71

In [23]:
# selects single row || loc - label based index
df.loc[df.name=="Rahul"]

    name  age Home_Town  marks
1  Rahul   21    Mumbai     78

In [24]:
# select multiple rows with conditions || loc - label based index
df.loc[(df.name=="Mangesh") & (df.age>=20)]

      name  age Home_Town  marks
0  Mangesh   20      Pune     96

#### 5) Filter Dataframe - Filtering by column values

In [29]:
# filter people having age more than equal to 20 into a new dataframe
df_age_filter=df[df['age']>=21]
df_age_filter

     name  age Home_Town  marks
1   Rahul   21    Mumbai     78
2    Amit   22    Nashik     71
5  Eshaan   23     Jammu     81

In [33]:
# multiple filter condition
df_multiple_filters=df[(df['age']>=22) & (df['marks']>=80)]
df_multiple_filters

     name  age Home_Town  marks
5  Eshaan   23     Jammu     81

In [36]:
# where function replace values in a DataFrame based on a condition

df.where(df['age']>21,other='NAN')

     name  age Home_Town marks
0     NAN  NAN       NAN   NAN
1     NAN  NAN       NAN   NAN
2    Amit   22    Nashik    71
3     NAN  NAN       NAN   NAN
4     NAN  NAN       NAN   NAN
5  Eshaan   23     Jammu    81

#### 6) Rows and Columns - Operation (Add, update, delete)

In [37]:
df

      name  age Home_Town  marks
0  Mangesh   20      Pune     96
1    Rahul   21    Mumbai     78
2     Amit   22    Nashik     71
3   Pratik   20    Gujrat     93
4    Aryan   19   Kashmir     86
5   Eshaan   23     Jammu     81

In [39]:
# Create a new column
df['Fav_Subject']=['Technology','Science','History','Politics','Geography','English']
df

      name  age Home_Town  marks Fav_Subject
0  Mangesh   20      Pune     96  Technology
1    Rahul   21    Mumbai     78     Science
2     Amit   22    Nashik     71     History
3   Pratik   20    Gujrat     93    Politics
4    Aryan   19   Kashmir     86   Geography
5   Eshaan   23     Jammu     81     English

In [40]:
# Add new columns using existing column/s
df['marks_percent']=df['marks']*100/100
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune     96  Technology           96.0
1    Rahul   21    Mumbai     78     Science           78.0
2     Amit   22    Nashik     71     History           71.0
3   Pratik   20    Gujrat     93    Politics           93.0
4    Aryan   19   Kashmir     86   Geography           86.0
5   Eshaan   23     Jammu     81     English           81.0

In [61]:
# Add new row - at the end of dataframe
df.loc[len(df)]=["Harshya",22,"Mehkar",99,"Marathi",99.0]
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune     96  Technology           96.0
1    Rahul   21    Mumbai     78     Science           78.0
2     Amit   22    Nashik     71     History           71.0
3   Pratik   20    Gujrat     93    Politics           93.0
4    Aryan   19   Kashmir     86   Geography           86.0
5   Eshaan   23     Jammu     81     English           81.0
6  Harshya   22    Mehkar     99     Marathi           99.0

In [56]:

# delete specific row
df.drop(3, axis=0)
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune     96  Technology           96.0
1    Rahul   21    Mumbai     78     Science           78.0
2     Amit   22    Nashik     71     History           71.0
3   Pratik   20    Gujrat     93    Politics           93.0
4    Aryan   19   Kashmir     86   Geography           86.0
5   Eshaan   23     Jammu     81     English           81.0

In [ ]:
# delete rows using column-value filter
df = df.drop(df[df.name == 'Harshya'].index) # delete row, axis= 0

In [62]:
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune     96  Technology           96.0
1    Rahul   21    Mumbai     78     Science           78.0
2     Amit   22    Nashik     71     History           71.0
3   Pratik   20    Gujrat     93    Politics           93.0
4    Aryan   19   Kashmir     86   Geography           86.0
5   Eshaan   23     Jammu     81     English           81.0
6  Harshya   22    Mehkar     99     Marathi           99.0

In [65]:
# sort values in ascending order
df.sort_values('marks')

      name  age Home_Town  marks Fav_Subject  marks_percent
2     Amit   22    Nashik     71     History           71.0
1    Rahul   21    Mumbai     78     Science           78.0
5   Eshaan   23     Jammu     81     English           81.0
4    Aryan   19   Kashmir     86   Geography           86.0
3   Pratik   20    Gujrat     93    Politics           93.0
0  Mangesh   20      Pune     96  Technology           96.0
6  Harshya   22    Mehkar     99     Marathi           99.0

In [70]:
# sort values in descending order
df.sort_values('marks',ascending = False)

      name  age Home_Town  marks Fav_Subject  marks_percent
6  Harshya   22    Mehkar     99     Marathi           99.0
0  Mangesh   20      Pune     96  Technology           96.0
3   Pratik   20    Gujrat     93    Politics           93.0
4    Aryan   19   Kashmir     86   Geography           86.0
5   Eshaan   23     Jammu     81     English           81.0
1    Rahul   21    Mumbai     78     Science           78.0
2     Amit   22    Nashik     71     History           71.0

#### 7) Handling Missing Values

In [71]:
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune     96  Technology           96.0
1    Rahul   21    Mumbai     78     Science           78.0
2     Amit   22    Nashik     71     History           71.0
3   Pratik   20    Gujrat     93    Politics           93.0
4    Aryan   19   Kashmir     86   Geography           86.0
5   Eshaan   23     Jammu     81     English           81.0
6  Harshya   22    Mehkar     99     Marathi           99.0

In [72]:
# detect null values
df.isnull()

    name    age  Home_Town  marks  Fav_Subject  marks_percent
0  False  False      False  False        False          False
1  False  False      False  False        False          False
2  False  False      False  False        False          False
3  False  False      False  False        False          False
4  False  False      False  False        False          False
5  False  False      False  False        False          False
6  False  False      False  False        False          False

In [81]:
# lets create a null value using numpy and creating a new row
df.loc[len(df)]=["Dablu",1,"Buldhana",60,"Playing",60.0]
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune     96  Technology           96.0
1    Rahul   21    Mumbai     78     Science           78.0
2     Amit   22    Nashik     71     History           71.0
3   Pratik   20    Gujrat     93    Politics           93.0
4    Aryan   19   Kashmir     86   Geography           86.0
5   Eshaan   23     Jammu     81     English           81.0
6  Harshya   22    Mehkar     99     Marathi           99.0
7    Dablu    1  Buldhana     60     Playing           60.0

In [79]:
df=df.drop(df[df.name=="Dablu"].index)

In [82]:
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune     96  Technology           96.0
1    Rahul   21    Mumbai     78     Science           78.0
2     Amit   22    Nashik     71     History           71.0
3   Pratik   20    Gujrat     93    Politics           93.0
4    Aryan   19   Kashmir     86   Geography           86.0
5   Eshaan   23     Jammu     81     English           81.0
6  Harshya   22    Mehkar     99     Marathi           99.0
7    Dablu    1  Buldhana     60     Playing           60.0

In [92]:
# add a null value using numpy
import numpy as np
df.loc[df.name=='Dablu', 'marks'] = np.nan

In [93]:
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune   96.0  Technology           96.0
1    Rahul   21    Mumbai   78.0     Science           78.0
2     Amit   22    Nashik   71.0     History           71.0
3   Pratik   20    Gujrat   93.0    Politics           93.0
4    Aryan   19   Kashmir   86.0   Geography           86.0
5   Eshaan   23     Jammu   81.0     English           81.0
6  Harshya   22    Mehkar   99.0     Marathi           99.0
7    Dablu    1  Buldhana    NaN     Playing           60.0

In [94]:
# now lets check , if there any null value ?

df.isnull()

    name    age  Home_Town  marks  Fav_Subject  marks_percent
0  False  False      False  False        False          False
1  False  False      False  False        False          False
2  False  False      False  False        False          False
3  False  False      False  False        False          False
4  False  False      False  False        False          False
5  False  False      False  False        False          False
6  False  False      False  False        False          False
7  False  False      False   True        False          False

In [97]:
# count of null values by columns
df.isnull().sum()

name             0
age              0
Home_Town        0
marks            1
Fav_Subject      0
marks_percent    0
dtype: int64

In [96]:
# lets fill null values with a number
df.fillna(900)

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune   96.0  Technology           96.0
1    Rahul   21    Mumbai   78.0     Science           78.0
2     Amit   22    Nashik   71.0     History           71.0
3   Pratik   20    Gujrat   93.0    Politics           93.0
4    Aryan   19   Kashmir   86.0   Geography           86.0
5   Eshaan   23     Jammu   81.0     English           81.0
6  Harshya   22    Mehkar   99.0     Marathi           99.0
7    Dablu    1  Buldhana  900.0     Playing           60.0

#### 8) Aggregation and Group By

In [109]:
# count the frequency of values in age column

df['age'].value_counts()

age
20    2
22    2
21    1
19    1
23    1
1     1
Name: count, dtype: int64

In [110]:
# count the frequency of values in city column

df['city'].value_counts()

KeyError: 'city'

In [111]:
# calculate the total of marks column

df['marks'].sum()

np.float64(604.0)

In [ ]:
# calculate the average of marks column
df['marks'].mean()

np.float64(86.28571428571429)

In [ ]:
# find the maximum value in marks column
df['marks'].max()

np.float64(99.0)

#### 9) AI and ChatGPT

In [99]:
df

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune   96.0  Technology           96.0
1    Rahul   21    Mumbai   78.0     Science           78.0
2     Amit   22    Nashik   71.0     History           71.0
3   Pratik   20    Gujrat   93.0    Politics           93.0
4    Aryan   19   Kashmir   86.0   Geography           86.0
5   Eshaan   23     Jammu   81.0     English           81.0
6  Harshya   22    Mehkar   99.0     Marathi           99.0
7    Dablu    1  Buldhana    NaN     Playing           60.0

In [ ]:
# Prompt to filter marks> 70 and age>20

In [105]:
# way 1 :General Method
df[(df['marks']>90) & (df['age']>=20)]

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune   96.0  Technology           96.0
3   Pratik   20    Gujrat   93.0    Politics           93.0
6  Harshya   22    Mehkar   99.0     Marathi           99.0

In [108]:
# way 2 :Query Method
df.query("marks>95 and age>=20")

      name  age Home_Town  marks Fav_Subject  marks_percent
0  Mangesh   20      Pune   96.0  Technology           96.0
6  Harshya   22    Mehkar   99.0     Marathi           99.0